// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcxEfOnQU1kpBaCRyeVz-9DD9bmYYDuh0',
    appId: '1:484317688280:web:0fac622bf206fde9ca42ad',
    messagingSenderId: '484317688280',
    projectId: 'fiberization-survey',
    authDomain: 'fiberization-survey.firebaseapp.com',
    storageBucket: 'fiberization-survey.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrX-xcfrDFB7CVXS4tjDw0cPlAKag5Q2Q',
    appId: '1:484317688280:android:2c1e49dc35ffc182ca42ad',
    messagingSenderId: '484317688280',
    projectId: 'fiberization-survey',
    storageBucket: 'fiberization-survey.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBe9YkkLZf_neaULoNRtAs7pa3zUrgLOgw',
    appId: '1:484317688280:ios:38b784f06af54c83ca42ad',
    messagingSenderId: '484317688280',
    projectId: 'fiberization-survey',
    storageBucket: 'fiberization-survey.firebasestorage.app',
    iosBundleId: 'com.mmr.blockSurvey',
  );
}
